### ISSUE TITLE
Not working with latest context api

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#14]
Using the latest React with the new context api is broken.

`react@16.3.0` Work
http://jsbin.com/joteqiluve/1/edit?html,js,console,output

`react@16.3.2` Doesn't work
http://jsbin.com/viyekexika/edit?html,js,console,output (**UPDATED LINK**)

**Comment by inlet** [comment]
Both jsbin examples seems to work correctly. 

The `<Stage>` is using the legacy context API which will be supported for all React 16.x versions:
https://reactjs.org/docs/legacy-context.html

You can use the `<Provider>` for exposing the `PIXI.Application`: 
https://github.com/inlet/react-pixi/blob/master/README.md#access-the-pixiapplication-in-child-components

Is your problem React related or related to this lib?

**Comment by EloB** [comment]
I provided wrong jsbin. I've updated the `1.6.3` link and now it's broken.

**Comment by EloB** [comment]
```
"Warning: Unexpected Fiber popped."
"Warning: Unexpected Fiber popped."
"Warning: Unexpected Fiber popped."
"Script error. (line 0)"
"The above error occurred in the <Stage> component:
    in Stage (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries."
"error"
"Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:185:19)
    at invokeGuardedCallback (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:227:29)
    at commitRoot (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12040:9)
    at completeRoot (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12948:36)
    at performWorkOnRoot (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12898:11)
    at performWork (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12816:9)
    at performSyncWork (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12793:5)
    at requestWork (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12693:7)
    at scheduleWorkImpl (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12568:13)
    at scheduleWork (https://unpkg.com/react-dom@16.3.2/umd/react-dom.development.js:12528:12)"
```

**Comment by inlet** [comment]
Would you be in for fixing this and create a PR? I can fix it, but not the coming days

**Comment by inlet** [comment]
It seems that the hostconfig is changed for the reconciler, I've created a PR and will fix this asap. Thanks for pointing out @EloB !

**Comment by inlet** [comment]
Done! 🙌
