### ISSUE TITLE
6.0.3 crashes yarn install

### ISSUE THREAD

**Issue by JohannesKlauss** [inlet/react-pixi#264]
### Description
Updating to 6.0.3 crashes the yarn postinstall step.

### Steps to reproduce

1. use 6.0.3
2. Run yarn install

Error:

```
error /Users/johannesklauss/Documents/Development/Syra/node_modules/@inlet/react-pixi: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments: 
Directory: /Users/johannesklauss/Documents/Development/Syra/node_modules/@inlet/react-pixi
Output:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/johannesklauss/Documents/Development/Syra/node_modules/@inlet/react-pixi/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

### Additional info

- `@inlet/react-pixi` version:  6.0.3
- `yarn` version: 1.22.4
- `OS`: macOS: 10.15.7

**Comment by inlet** [comment]
Oop forgot to add the `postinstall.js` to npm files.. just a sec

**Comment by inlet** [comment]
Fix is on its way 😉

**Comment by inlet** [comment]
Done!
