### ISSUE TITLE
Support pixi-tiled

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#267]
# Description
I need to load [Tiled](https://www.mapeditor.org/) maps in my application, and found that [pixi-tiled](https://github.com/eXponenta/pixi-tiled) supports Pixi.js v5.

Unfortunately, it doesn't seem to work. [Reading the code](https://github.com/eXponenta/pixi-tiled/blob/f1e02e549cba4009ee3b5afebf9ef61443c63b85/src/index.ts#L29), I tried the following:

```tsx
import React, { useEffect} from "react";
import { Application, useApp } from "pixi.js";
import { Parser } from "pixiv5-tiled";

Application.registerPlugin(Parser);

const MyMap: React.FC = () => {
  const app = useApp();
  useEffect(() => {
    app.loader.add("map", "../assets/atlas/test-map.json").load(() => {
      console.dir(app.loader.resources["map"]);
    });
  });

  ...
};
```

Error:
![](https://i.imgur.com/ZBTFeKs.png)

<details><summary>logs</summary>

```
app.es.js:78 Uncaught TypeError: Cannot read property 'call' of undefined
    at app.es.js:78
    at Array.forEach (<anonymous>)
    at new Application (app.es.js:77)
    at Stage.componentDidMount (react-pixi.es-dev.js:22974)
    at commitLifeCycles (react-dom.development.js:21527)
    at commitLayoutEffects (react-dom.development.js:24369)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:24082)
(anonymous) @ app.es.js:78
Application @ app.es.js:77
componentDidMount @ react-pixi.es-dev.js:22974
commitLifeCycles @ react-dom.development.js:21527
commitLayoutEffects @ react-dom.development.js:24369
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:24082
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
commitRoot @ react-dom.development.js:23913
finishConcurrentRender @ react-dom.development.js:23107
performConcurrentWorkOnRoot @ react-dom.development.js:22985
workLoop @ scheduler.development.js:590
flushWork @ scheduler.development.js:545
performWorkUntilDeadline @ scheduler.development.js:157
react-dom.development.js:20945 The above error occurred in the <Stage> component:

    at Stage (https://localhost:9000/2.bundle.js:22960:5)
    at div
    at Demo (https://localhost:9000/12.bundle.js:182:79)
    at Suspense
    at Route (https://localhost:9000/app.bundle.js:116675:673)
    at Routes (https://localhost:9000/app.bundle.js:116679:23)
    at Suspense
    at ErrorBoundary (https://localhost:9000/app.bundle.js:132735:43)
    at main
    at App (https://localhost:9000/app.bundle.js:46154:33)
    at ApolloProvider (https://localhost:9000/app.bundle.js:7051:21)
    at ApolloPersistentProvider (https://localhost:9000/app.bundle.js:132663:21)
    at Suspense
    at ErrorBoundary (https://localhost:9000/app.bundle.js:132735:43)
    at Router (https://localhost:9000/app.bundle.js:116677:23)
    at BrowserRouter (https://localhost:9000/app.bundle.js:116614:23)
    at Main

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:20945
update.payload @ react-dom.development.js:20993
getStateFromUpdate @ react-dom.development.js:12469
processUpdateQueue @ react-dom.development.js:12617
updateClassInstance @ react-dom.development.js:13392
updateClassComponent @ react-dom.development.js:18009
beginWork @ react-dom.development.js:19875
beginWork$1 @ react-dom.development.js:24928
performUnitOfWork @ react-dom.development.js:23699
workLoopSync @ react-dom.development.js:23618
renderRootSync @ react-dom.development.js:23577
performSyncWorkOnRoot @ react-dom.development.js:23165
(anonymous) @ react-dom.development.js:11534
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
flushSyncCallbackQueueImpl @ react-dom.development.js:11529
flushSyncCallbackQueue @ react-dom.development.js:11516
commitRootImpl @ react-dom.development.js:24223
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
commitRoot @ react-dom.development.js:23913
finishConcurrentRender @ react-dom.development.js:23107
performConcurrentWorkOnRoot @ react-dom.development.js:22985
workLoop @ scheduler.development.js:590
flushWork @ scheduler.development.js:545
performWorkUntilDeadline @ scheduler.development.js:157
react-pixi.es-dev.js:20678 Uncaught TypeError: Cannot read property 'current' of undefined
    at Object.updateContainer (react-pixi.es-dev.js:20678)
    at Stage.componentWillUnmount (react-pixi.es-dev.js:23059)
    at callComponentWillUnmountWithTimer (react-dom.development.js:21277)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at safelyCallComponentWillUnmount (react-dom.development.js:21284)
    at commitUnmount (react-dom.development.js:21815)
    at commitNestedUnmounts (react-dom.development.js:21868)
    at unmountHostComponents (react-dom.development.js:22154)
updateContainer @ react-pixi.es-dev.js:20678
componentWillUnmount @ react-pixi.es-dev.js:23059
callComponentWillUnmountWithTimer @ react-dom.development.js:21277
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
safelyCallComponentWillUnmount @ react-dom.development.js:21284
commitUnmount @ react-dom.development.js:21815
commitNestedUnmounts @ react-dom.development.js:21868
unmountHostComponents @ react-dom.development.js:22154
commitDeletion @ react-dom.development.js:22219
commitMutationEffects @ react-dom.development.js:24346
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:24052
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
commitRoot @ react-dom.development.js:23913
performSyncWorkOnRoot @ react-dom.development.js:23201
(anonymous) @ react-dom.development.js:11534
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
flushSyncCallbackQueueImpl @ react-dom.development.js:11529
flushSyncCallbackQueue @ react-dom.development.js:11516
commitRootImpl @ react-dom.development.js:24223
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
commitRoot @ react-dom.development.js:23913
finishConcurrentRender @ react-dom.development.js:23107
performConcurrentWorkOnRoot @ react-dom.development.js:22985
workLoop @ scheduler.development.js:590
flushWork @ scheduler.development.js:545
performWorkUntilDeadline @ scheduler.development.js:157
Show 4 more frames
react-dom.development.js:20945 The above error occurred in the <Stage> component:

    at Stage (https://localhost:9000/2.bundle.js:22960:5)
    at div
    at Demo (https://localhost:9000/12.bundle.js:182:79)
    at Suspense
    at Route (https://localhost:9000/app.bundle.js:116675:673)
    at Routes (https://localhost:9000/app.bundle.js:116679:23)
    at Suspense
    at ErrorBoundary (https://localhost:9000/app.bundle.js:132735:43)
    at main
    at App (https://localhost:9000/app.bundle.js:46154:33)
    at ApolloProvider (https://localhost:9000/app.bundle.js:7051:21)
    at ApolloPersistentProvider (https://localhost:9000/app.bundle.js:132663:21)
    at Suspense
    at ErrorBoundary (https://localhost:9000/app.bundle.js:132735:43)
    at Router (https://localhost:9000/app.bundle.js:116677:23)
    at BrowserRouter (https://localhost:9000/app.bundle.js:116614:23)
    at Main

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:20945
update.payload @ react-dom.development.js:20993
getStateFromUpdate @ react-dom.development.js:12469
processUpdateQueue @ react-dom.development.js:12617
updateClassInstance @ react-dom.development.js:13392
updateClassComponent @ react-dom.development.js:18009
beginWork @ react-dom.development.js:19875
beginWork$1 @ react-dom.development.js:24928
performUnitOfWork @ react-dom.development.js:23699
workLoopSync @ react-dom.development.js:23618
renderRootSync @ react-dom.development.js:23577
performSyncWorkOnRoot @ react-dom.development.js:23165
(anonymous) @ react-dom.development.js:11534
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
flushSyncCallbackQueueImpl @ react-dom.development.js:11529
flushSyncCallbackQueue @ react-dom.development.js:11516
commitRootImpl @ react-dom.development.js:24223
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11483
commitRoot @ react-dom.development.js:23913
finishConcurrentRender @ react-dom.development.js:23107
performConcurrentWorkOnRoot @ react-dom.development.js:22985
workLoop @ scheduler.development.js:590
flushWork @ scheduler.development.js:545
performWorkUntilDeadline @ scheduler.development.js:157
```

</details>

### Additional info

- `@inlet/react-pixi` version: 6.0.5
- `React` version: experimental
- `ReactDOM` version: experimental
- `PIXI` version: 5.3.3
- `Pixiv5-tiled` version: 1.1.17

**Comment by inlet** [comment]
```jsx
import { Application, useApp } from "pixi.js";
```

`useApp` does not exist in `pixi.js` but in this lib `@inlet/react-pixi` :wink:

**Comment by AdrienLemaire** [comment]
@inlet fixed the example, this was a typo obviously, else it would have thrown a different error). You are really quick to close issues.
Pixiv5-tiled works fine with Pixi.js v5, not with `@inlet/react-pixi`, and I do not have the skills to fix your repository code atm...

**Comment by inlet** [comment]
It would be helpful if you could create a sample on codesandbox/codepen to pinpoint the issue. This would save me time.

Thanks in advance!
